linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - gosimple
    - gocritic
    - revive
    - misspell
    - unconvert
    - unparam
    - gosec

linters-settings:
  revive:
    rules:
      - name: exported
        disabled: true
  gocritic:
    disabled-checks:
      - exitAfterDefer

run:
  timeout: 2m
